#!/usr/bin/env Rscript
# Regenerate from the package root:
# Rscript test/fixtures/r/s50_targets.R > test/fixtures/s50_targets.toml
# Uses RSiena's own bundled s50 observations; the Julia tests verify identical
# bundled inputs. Targets are deterministic, so no stochastic fit or seed is used.
suppressPackageStartupMessages(library(RSiena))
seed <- 20260914L
set.seed(seed) # no random draws are needed for these deterministic targets
d <- sienaDataCreate(
    friendship = sienaDependent(array(c(s501, s502, s503), dim = c(50, 50, 3))),
    alcohol = sienaDependent(s50a, type = "behavior"),
    smoke1 = coCovar(s50s[, 1]))
e <- getEffects(d)
e$include <- FALSE
specs <- list(
    c("friendship", "Rate", "", "rate"),
    c("alcohol", "Rate", "", "rate"),
    c("friendship", "density", "", "eval"),
    c("friendship", "recip", "", "eval"),
    c("friendship", "transTrip", "", "eval"),
    c("friendship", "transMedTrip", "", "eval"),
    c("friendship", "transRecTrip", "", "eval"),
    c("friendship", "cycle3", "", "eval"),
    c("friendship", "transTies", "", "eval"),
    c("friendship", "between", "", "eval"),
    c("friendship", "nbrDist2", "", "eval"),
    c("friendship", "denseTriads", "", "eval"),
    c("friendship", "inPop", "", "eval"),
    c("friendship", "inPopSqrt", "", "eval"),
    c("friendship", "outPop", "", "eval"),
    c("friendship", "outAct", "", "eval"),
    c("friendship", "outActSqrt", "", "eval"),
    c("friendship", "inAct", "", "eval"),
    c("friendship", "isolateNet", "", "eval"),
    c("friendship", "altX", "smoke1", "eval"),
    c("friendship", "egoX", "smoke1", "eval"),
    c("friendship", "simX", "smoke1", "eval"),
    c("friendship", "sameX", "smoke1", "eval"),
    c("friendship", "egoXaltX", "smoke1", "eval"),
    c("alcohol", "linear", "", "eval"),
    c("alcohol", "quad", "", "eval"),
    c("alcohol", "avSim", "friendship", "eval"),
    c("alcohol", "totSim", "friendship", "eval"),
    c("alcohol", "indeg", "friendship", "eval"),
    c("alcohol", "outdeg", "friendship", "eval"),
    c("alcohol", "avAlt", "friendship", "eval"),
    c("alcohol", "effFrom", "smoke1", "eval"))
indices <- unlist(lapply(specs, function(s) {
    ids <- which(e$name == s[1] & e$shortName == s[2] &
                 e$interaction1 == s[3] & e$type == s[4])
    stopifnot(length(ids) == if (s[4] == "rate") 2 else 1)
    ids
}))
e$include[indices] <- TRUE
selected <- e[e$include, ]
# getTargets returns one row per effect and one column per observation period.
targets <- RSiena:::getTargets(d, e)
stopifnot(nrow(targets) == nrow(selected))
values <- rowSums(targets)
# Basic rates are period-specific: getTargets has structural zeros in other periods.
values <- values[match(indices, which(e$include))]
cat("# Generated by RSiena, not transcribed from Julia output.\n[provenance]\n")
cat(sprintf('r_version = "%s"\nrsiena_version = "%s"\n', getRversion(), packageVersion("RSiena")))
cat(sprintf('seed = %d\n', seed))
cat('script = "test/fixtures/r/s50_targets.R"\n')
cat(sprintf('date = "%s"\n', Sys.Date()))
cat('dataset = "RSiena::s50: three friendship/alcohol waves, centered smoke1"\n')
cat('method = "RSiena:::getTargets; unconditional MoM; sum across periods"\n')
cat('\n[tolerance]\n# Deterministic targets; tolerance covers floating-point summation only.\ntargets = 1e-9\n')
cat('\n[values]\n')
cat(sprintf('targets = [%s]\n', paste(sprintf("%.17g", values), collapse = ", ")))
cat(sprintf('effect_names = [%s]\n', paste(sprintf('"%s"', e$effectName[indices]), collapse = ", ")))
cat('\n[coverage]\n')
cat('scope = "34 rate, network and behavior targets; not the full catalogue"\n')
cat('not_equivalent = ["balanceSimple", "avAttHigherSimple", "avAttLowerSimple"]\n')
cat('not_implemented = ["include_interaction!", "forcing/initiative network model types"]\n')
